import { ArtifactView } from '../core/domain/models/artifact-view';

export const defaultArtifactsViews: ArtifactView[] = [
  {
    id: '0',
    type: 'flower',
    set: 'Gladiators Finale',
    level: 8,
    mainStat: '2342 HP',
    subStat1: '16 ATK',
    subStat2: '4.7% ATK',
    subStat3: '11.7% Crit DMG',
    subStat4: '4.5% Energy Recharge',
  },
  {
    id: '1',
    type: 'plume',
    set: 'Crimson Witch Of Flames',
    level: 8,
    mainStat: '152 ATK',
    subStat1: '478 HP',
    subStat2: '7.8% Crit DMG',
    subStat3: '3.1% Crit Rate',
    subStat4: '5.8% Energy Recharge',
  },
  {
    id: '2',
    type: 'sands',
    set: 'Archaic Petra',
    level: 8,
    mainStat: '22.8% ATK',
    subStat1: '16 Elemental Mastery',
    subStat2: '538 HP',
    subStat3: '3.5% Crit Rate',
    subStat4: '5.2% Energy Recharge',
  },
  {
    id: '3',
    type: 'goblet',
    set: 'Bloodstained Chivalry',
    level: 0,
    mainStat: '7% Pyro DMG',
    subStat1: '21 Elemental Mastery',
    subStat2: '4.7% HP',
    subStat3: '4.5% Energy Recharge',
    subStat4: '19 ATK',
  },
  {
    id: '4',
    type: 'circlet',
    set: 'Gladiators Finale',
    level: 16,
    mainStat: '38.7% ATK',
    subStat1: '53 ATK',
    subStat2: '37 DEF',
    subStat3: '19 Elemental Mastery',
    subStat4: '7.6% DEF',
  },
];
