name: Continuous Integration/Development

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run lint
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run test:adapters
      - run: bash <(curl -s https://codecov.io/bash) -F adapters
      - run: npm run test:domain
      - run: bash <(curl -s https://codecov.io/bash) -F domain
