name: Continuous Integration/Development

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run lint
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run test:adapters
      - run: bash <(curl -s https://codecov.io/bash) -F adapters
      - run: npm run test:domain
      - run: bash <(curl -s https://codecov.io/bash) -F domain
  build-and-deploy:
    needs: [lint, test]
    if: contains(github.ref, 'master') || contains(github.ref, 'cicd')
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: |
          npm install
          npm run build:test

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build