name: Build & Deploy Release

on:
  push:
    branches: [ cicd/* ]
  release:
    types: [published]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: |
          npm install
          npm run build:prod
  deploy:
    needs: [build]
    name:  deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Deploy 🚀
        run: |
          wget https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip
          unzip packer_1.3.1_linux_amd64.zip
          sudo apt-get update
          sudo apt-get install jq
          python3 -m venv venv3
          . ./venv3/bin/activate
          pip install --upgrade pip
          pip install python-openstackclient
          OS_AUTH_URL=${{secrets.OS_AUTH_URL}}
          OS_USERNAME=${{secrets.OS_USERNAME}}
          OS_PASSWORD=${{secrets.OS_PASSWORD}}
          OS_TENANT_NAME=${{secrets.OS_TENANT_NAME}}
          OS_USERNAME=${{secrets.OS_USERNAME}}
          SOURCE_ID=`openstack image list -f json | jq -r '.[] | select(.Name == "Debian 10") | .ID'`
          FLAVOR_ID=`openstack flavor list -f json | jq -r '.[] | select(.Name == "d2-2") | .ID'`
          NETWORK_ID=`openstack network list -f json | jq -r '.[] | select(.Name == "Ext-Net") | .ID'`
          chmod +x deploy/build-packer-json.sh
          deploy/build-packer-json.sh
          ./packer build packer.json
          IMAGE_ID=`openstack image list -f json | jq -r '.[] | select(.Name == "genshin-bo/${GITHUB_REF##*/}") | .ID'`
          openstack server rebuild --image IMAGE_ID genshin-bo-front
